// apps/client/src/components/layout/bookmark-layout/header.tsx
import { Plus, Menu } from "lucide-react"
import { Button } from "@/components/ui/button"
import { CommandMenu } from "@/components/command-menu"
import { Bookmark } from '@/types/bookmark'
import { Sheet, SheetContent, SheetTrigger, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { cn } from "@/lib/utils"
import { SidebarContent } from "./sidebar-content"

interface HeaderProps {
  bookmarks: Bookmark[]
  onAddBookmark: () => void
}

export function Header({ bookmarks, onAddBookmark }: HeaderProps) {
  return (
    <div className="border-b border-border bg-background">
      <div className="flex h-16 items-center px-4 md:px-8">
        {/* 移动端侧边栏控制按钮 */}
        <div className="md:hidden">
          <Sheet>
            <SheetTrigger asChild>
              <Button
                variant="ghost"
                className={cn(
                  "px-2 text-base hover:bg-transparent hover:opacity-75",
                  "focus-visible:ring-0 focus-visible:ring-offset-0"
                )}
              >
                <Menu className="h-6 w-6" />
                <span className="sr-only">打开菜单</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="w-[240px] p-0 [&>button]:hidden">
              <SheetHeader className="sr-only">
                <SheetTitle>书签导航菜单</SheetTitle>
              </SheetHeader>
              <SidebarContent />
            </SheetContent>
          </Sheet>
        </div>

        <div className="flex-1 flex items-center space-x-4">
          <div className="flex-1 relative">
            <CommandMenu bookmarks={bookmarks} />
          </div>
          <Button onClick={onAddBookmark}>
            <Plus className="w-5 h-5" />
            <span>新增书签</span>
          </Button>
        </div>
      </div>
    </div>
  )
}

// apps/web/src/components/layout/header.vue
<script setup lang="ts"></script>

<template>
  <div class="border-b border-b-gray-200 dark:border-b-gray-700 bg-white dark:bg-gray-900">
    <div class="flex items-center px-4 md:px-8 py-2 md:py-4 space-x-4 sm:space-x-2">
      <!-- 移动端侧边栏 -->
      <u-drawer direction="left" :handle="false">
        <div class="md:hidden">
          <u-icon name="i-gravity-ui-text-align-justify" class="size-6 block"></u-icon>
        </div>
        <template #content>
          <layout-sidebar-content />
        </template>
      </u-drawer>
      <div class="flex-1 flex items-center space-x-4 sm:space-x-2">
        <div class="flex-1 relative">
          <layout-command-menu />
        </div>
        <u-button icon="i-gravity-ui-plus" class="btn" size="lg" @click="$emit('add-bookmark')">
          <span>新增书签</span>
        </u-button>
      </div>
    </div>
  </div>
</template>
